<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro">

<xacro:include filename="inertial_macros.xacro"/>

<!-- Define robot constants -->
<!-- Measured from Fusion Model-->
  <xacro:property name="base_width" value="0.58"/>
  <xacro:property name="base_length" value="0.66"/>
  <xacro:property name="base_height" value="0.32"/>

<!-- Measured from Fusion Model-->
  <xacro:property name="wheel_radius" value="0.12"/>
  <xacro:property name="wheel_width" value="0.05"/>
  <xacro:property name="wheel_ygap" value="0.3"/>
  <xacro:property name="wheel_zoff" value="0.01"/>
  <xacro:property name="wheel_xoff" value="0.20"/>
  
  <!-- <xacro:property name="caster_radius" value="0.08"/> -->
  <xacro:property name="caster_width" value="0.047"/>
  <xacro:property name="caster_ygap" value="-0.285"/>
  <xacro:property name="caster_zoff" value="0.0985"/>
  <xacro:property name="caster_xoff" value="-0.0375"/>

<!-- Robot base link -->

  <link name="base_footprint">
  </link>

 <joint name="base_joint" type="fixed">
    <parent link="base_link"/>
    <child link="base_footprint"/>
    <origin xyz="0.0 0.0 ${-(wheel_radius+wheel_zoff)}" rpy="0 0 0"/>
  </joint> 



<!-- Robot Chassis -->
  <link name="base_link">
    <visual>
      <origin rpy="0 0 0" xyz="0.0 -0.18 0.10"/>
      <geometry>
        <mesh filename="file:///$(find scootbot)/description/models/frame.stl" scale="0.001 0.001 0.001"/>
      </geometry>
      <material name="Gray">
          <color rgba="0.5 0.5 0.5 1.0"/>
        </material>
    </visual>
   <collision>
      <origin rpy="0 0 0" xyz="0.05 0 -0.06 "/>
      <geometry>
        <!-- <mesh filename="file:///$(find scootbot)/description/models/frame.stl" scale="0.001 0.001 0.001"/> -->
        <box size="0.468 0.39 0.10"/>
      </geometry>
    </collision>
  </link>

  <gazebo reference="base_link">
    <material>Gazebo/Grey</material>
  </gazebo>

 <!-- Inertial link stores the robot's inertial information - Chassis (31 Kg) + 2x Battery (5.5 Kg Each) = 42 Kg -->
  <link name="inertial_link">
    <xacro:inertial_box mass="42" x="0.5" y="0.4" z="0.21">
            <origin xyz="0.1 0 0" rpy="0 0 0"/>
    </xacro:inertial_box>
    <!-- <inertial>
      <mass value="46.034" />
      <origin xyz="0 0 0" />
      <inertia ixx="0.6022" ixy="-0.02364" ixz="-0.1197" iyy="1.7386" iyz="-0.001544" izz="2.0296" />
    </inertial> -->
  </link>

  <joint name="inertial_joint" type="fixed">
    <origin xyz="0 0 0.02" rpy="0 0 0" />
    <parent link="base_link" />
    <child link="inertial_link" />
  </joint>

<!-- Wheels -->
<xacro:macro name="wheel" params="prefix x_reflect y_reflect mirror x y col_x col_y col_z">
  <link name="${prefix}_link">

    <contact>
      <lateral_friction value="1.0"/>
      <rolling_friction value="1.0"/>
      <stiffness value="30000"/>
      <damping value="1000"/>
    </contact>
    
    <xacro:inertial_cylinder mass="2" length="0.08" radius="0.125">
      <origin xyz="0 0 0" rpy="0 0 0"/>
    </xacro:inertial_cylinder>

      <visual>
        <origin xyz="${x} ${y} -0.135" rpy="${pi/2} 0 ${mirror} "/>
        <geometry>
          <mesh filename="file:///$(find scootbot)/description/models/tyre.obj" scale="0.002 0.002 0.002"/>
        </geometry>
        <material name="Gray">
          <color rgba="0.5 0.5 0.5 1.0"/>
        </material>
      </visual>

     <collision>
        <origin xyz="${col_x} ${col_y} ${col_z}" rpy="${pi/2} 0 ${mirror} "/>
        <geometry>
            <cylinder radius="0.13" length="0.09"/>
        </geometry>
        <material name="Gray">
          <color rgba="0.5 0.5 0.5 1.0"/>
        </material>
      </collision>

  </link> 
     
    <gazebo reference="${prefix}_link">
			<mu1 value="1.0"/>
			<mu2 value="1.0"/>
			<kp value="10000000.0" />
			<kd value="1.0" />
			<fdir1 value="1 0 0"/>
		</gazebo>

    <joint name="drivewhl_${prefix}_joint" type="continuous">
      <parent link="base_link"/>
      <child link="${prefix}_link"/>
      <origin xyz="${x_reflect*wheel_xoff} ${y_reflect*(base_width/2+wheel_ygap)} ${-wheel_zoff}" rpy="0 0 0"/>
      <axis xyz="0 1 0"/>
    </joint>
</xacro:macro> 

  <xacro:wheel prefix="l" x_reflect="1" y_reflect="0.43" mirror="0" x="-0.135" y="-0.05" col_x="0" col_y="0.0" col_z="0"/>
  <xacro:wheel prefix="r" x_reflect="1" y_reflect="-0.47" mirror="3.15" x="0.135" y="0.065" col_x="0" col_y="0.0144" col_z="0"/>
 
<!-- Caster Frame -->

<xacro:macro name="caster_frame" params="prefix x_reflect y_reflect">

    <link name="caster_frame_${prefix}_link">

      <visual>
        <origin xyz="0.22 -0.005 0.074" rpy="0 0 0"/>
        <geometry>
            <mesh filename="file:///$(find scootbot)/description/models/caster_frame.obj" scale="0.001 0.001 0.001"/>
        </geometry>
        <material name="Gray">
          <color rgba="0.5 0.5 0.5 1.0"/>
        </material>
      </visual>
     <collision>
        <origin xyz="0.22 -0.005 0.075" rpy="0 0 0"/>
        <geometry>
          <mesh filename="file:///$(find scootbot)/description/models/caster_frame.obj" scale="0.001 0.001 0.001"/>
        </geometry>
      </collision>
      <xacro:inertial_box mass="1.5" x="0.05" y="0.1" z="0.1">
        <origin xyz="0 0 0" rpy="0 0 0"/>
      </xacro:inertial_box>
    </link> 

    <joint name="caster_frame_${prefix}_joint" type="continuous">
      <parent link="base_link"/>
      <child link="caster_frame_${prefix}_link"/>
      <origin xyz="-0.221 ${y_reflect} 0.026" rpy="0 0 0"/>
      <axis xyz="0 0 1"/>
    </joint>
    
    <gazebo reference="caster_frame_${prefix}_link">
      <mu1 value="0.7"/>
			<mu2 value="0.9"/>
			<kp value="2.0" />
			<kd value="1.0" />
			<fdir1 value="1 0 0"/>
    </gazebo>

  </xacro:macro> 

<xacro:caster_frame prefix="l" x_reflect="1" y_reflect="-0.1752"/>
<xacro:caster_frame prefix="r" x_reflect="1" y_reflect="0.1752"/>

<!-- Caster Wheels -->
  <xacro:macro name="caster_wheel" params="prefix x_reflect y_reflect caster_radius">
    <link name="casterwhl_${prefix}_link">
      <visual>
              <contact>
      <lateral_friction value="1.0"/>
      <rolling_friction value="1.0"/>
      <stiffness value="30000"/>
      <damping value="1000"/>
    </contact>
        <!-- <origin xyz="0.22 -0.165 -0.01" rpy="${pi/2} 0 0"/> -->
        <origin xyz="0 0 0.0" rpy="${pi/2} 0 0"/>
        <geometry>
            <cylinder radius="${caster_radius}" length="${caster_width}"/>
        </geometry>
        <material name="Gray">
          <color rgba="0.5 0.5 0.5 1.0"/>
        </material>
      </visual>
     <collision>
        <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
        <geometry>
          <cylinder radius="${caster_radius}" length="0.05"/>
          <!-- <sphere radius="0.1"/> -->
        </geometry>
      </collision>

      <xacro:inertial_cylinder mass="0.586" length="${caster_width}" radius="${caster_radius}">
        <origin xyz="0 0 0" rpy="0 0 0"/>
      </xacro:inertial_cylinder>

    </link> 

    <joint name="casterwhl_${prefix}_joint" type="continuous">
      <parent link="caster_frame_${prefix}_link"/>
      <child link="casterwhl_${prefix}_link"/>
      <origin xyz="${x_reflect*caster_xoff} ${y_reflect*(base_width/2+caster_ygap)} ${-caster_zoff}" rpy="0 0 0"/>
      <axis xyz="0 1 0"/>
    </joint>

    <gazebo reference="casterwhl_${prefix}_link">
      <mu1 value="2000.0"/>
			<mu2 value="1000.0"/>
			<kp value="10000000.0" />
			<kd value="1.0" />
			<fdir1 value="1 0 0"/>
    </gazebo>

  </xacro:macro> 

  <xacro:caster_wheel prefix="l" x_reflect="1" y_reflect="0.47" caster_radius="0.0721"/>
  <xacro:caster_wheel prefix="r" x_reflect="1" y_reflect="-0.47" caster_radius="0.072"/>

 <joint name="laser_joint" type="fixed">
        <parent link="base_link"/>
        <child link="laser_frame"/>
        <origin xyz="0.25 -0.005 0.18" rpy="0 0 0"/>
    </joint>
 
        <link name="laser_frame">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
            <cylinder radius="0.04" length="0.04"/>
        </geometry>
      </visual>
     <!-- <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <cylinder radius="0.04" length="0.04"/>
        </geometry>
      </collision> -->

    <!-- <inertial>
        <mass value="1"/>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <inertia ixx="0.000419" ixy="-0.000000" ixz="0.000000" iyy="0.00744" iyz="0.000000" izz="0.000419"/>
      </inertial> -->

    </link> 

<gazebo reference="laser_frame">
        <mu1 value="400"/>
        <mu2 value="400"/>
        <kp value="10000000.0"/>
        <kd value="1.0"/>
        <minDepth>0.01</minDepth>
        <material>Gazebo/Grey</material>
        <turnGravityOff>false</turnGravityOff>
        <sensor name="laser" type="ray">
            <pose> 0 0 0 0 0.1 0 </pose>
            <visualize>false</visualize>
            <update_rate>10</update_rate>
            <ray>
                <scan>
                    <horizontal>
                        <samples>360</samples>
                        <min_angle>-3.14</min_angle>
                        <max_angle>3.14</max_angle>
                    </horizontal>
                </scan>
                <range>
                    <min>0.3</min>
                    <max>12</max>
                </range>
            </ray>
            <plugin name="laser_controller" filename="libgazebo_ros_ray_sensor.so">
                <ros>
                    <argument>~/out:=scan</argument>
                </ros>
                <output_type>sensor_msgs/LaserScan</output_type>
                <frame_name>laser_frame</frame_name>
            </plugin>
        </sensor>
    </gazebo>
    
</robot>