<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro">

<!-- Define robot constants -->
<!-- Measured from Fusion Model-->
  <xacro:property name="base_width" value="0.58"/>
  <xacro:property name="base_length" value="0.66"/>
  <xacro:property name="base_height" value="0.32"/>

<!-- Measured from Fusion Model-->
  <xacro:property name="wheel_radius" value="0.12"/>
  <xacro:property name="wheel_width" value="0.05"/>
  <xacro:property name="wheel_ygap" value="0.3"/>
  <xacro:property name="wheel_zoff" value="0.01"/>
  <xacro:property name="wheel_xoff" value="0.20"/>
  
  <xacro:property name="caster_radius" value="0.075"/>
  <xacro:property name="caster_width" value="0.04"/>
  <xacro:property name="caster_ygap" value="-0.285"/>
  <xacro:property name="caster_zoff" value="0.0985"/>
  <xacro:property name="caster_xoff" value="-0.0375"/>

<link name="dummy">
   </link>
<!-- Robot Base -->
  <link name="base_link">
    <visual>
      <origin rpy="0 0 0" xyz="0.0 -0.18 0.10"/>
      <geometry>
        <mesh filename="file:///home/ubuntu/scootbot/install/scootbot_description/share/scootbot_description/src/description/frame.stl" scale="0.001 0.001 0.001"/>
      </geometry>
    </visual>
   <collision>
      <origin rpy="0 0 0" xyz="0 0 0.05 "/>
      <geometry>
        <!-- <mesh filename="file:///home/ubuntu/scootbot/install/scootbot_description/share/scootbot_description/src/description/frame.stl" scale="0.001 0.001 0.001"/> -->
        <box size="0.663 0.39 0.312"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="10"/>
      <origin xyz="0 0 0"/>
      <!--
        | ixx="-0.999998" ixy="-0.000077" ixz="0.001926" |
        | ixy="-0.000078" iyy="1.000000" iyz="-0.000611" |
        | ixz="-0.001926" iyz="-0.000611" izz="-0.999998" |
        -->
      <!-- <inertia ixx="-0.999998" ixy="-0.000077" ixz="-0.001926" iyy="1.000000" iyz="-0.000611" izz="-0.999998"/> -->
      <inertia ixx="0" ixy="0" ixz="0" iyy="0" iyz="0" izz="0"/>
    </inertial>
  </link>
  <joint name="dummy_joint" type="fixed">
     <parent link="dummy"/>
     <child link="base_link"/>
   </joint>
  <gazebo reference="base_link">
    <material>Gazebo/Grey</material>
  </gazebo>

<!-- Robot Footprint -->
  <link name="base_footprint"/>

 <joint name="base_joint" type="fixed">
    <parent link="base_link"/>
    <child link="base_footprint"/>
    <origin xyz="0.0 0.0 ${-(wheel_radius+wheel_zoff)}" rpy="0 0 0"/>
  </joint> 

<!-- Wheels -->
<xacro:macro name="wheel" params="prefix x_reflect y_reflect mirror x y col_x col_y col_z">
  <link name="${prefix}_link">
    <!-- <contact>
      <lateral_friction value="1.0"/>
      <rolling_friction value="0.0"/>
      <stiffness value="30000"/>
      <damping value="1000"/>
    </contact> -->
    
    <inertial>
      <mass value="1"/>
      <origin xyz="0 0 0"/>
      <!--
        | ixx="0.000819" ixy="-0.000000" ixz="0.000000" |
        | ixy="-0.000000" iyy="0.001344" iyz="0.000000" |
        | ixz="0.000000" iyz="0.000000" izz="0.000819" |
        -->
      <inertia ixx="0.000819" ixy="-0.000000" ixz="0.000000" iyy="0.001344" iyz="0.000000" izz="0.000819"/>
    </inertial>
      <visual>
        <origin xyz="${x} ${y} -0.135" rpy="${pi/2} 0 ${mirror} "/>
        <geometry>
          <mesh filename="file:///home/ubuntu/scootbot/install/scootbot_description/share/scootbot_description/src/description/tyre.obj" scale="0.002 0.002 0.002"/>
        </geometry>
        <material name="Gray">
          <color rgba="0.5 0.5 0.5 1.0"/>
        </material>
      </visual>
     <collision>
        <origin xyz="${col_x} ${col_y} ${col_z}" rpy="${pi/2} 0 ${mirror} "/>
        <geometry>
            <cylinder radius="0.135" length="0.09"/>
        </geometry>
        <material name="Gray">
          <color rgba="0.5 0.5 0.5 1.0"/>
        </material>
      </collision>
    </link> 
     
    <gazebo reference="${prefix}_link">
      <mu1 value="100"/>
      <mu2 value="100"/>
      <kp value="10000000.0"/>
      <kd value="1.0"/>
      <fdir1 value="1 0 0"/>
      <material>Gazebo/Grey</material>
      <turnGravityOff>false</turnGravityOff>
    </gazebo>

    <joint name="drivewhl_${prefix}_joint" type="continuous">
      <parent link="base_link"/>
      <child link="${prefix}_link"/>
      <origin xyz="${x_reflect*wheel_xoff} ${y_reflect*(base_width/2+wheel_ygap)} ${-wheel_zoff}" rpy="0 0 0"/>
      <axis xyz="0 1 0"/>
    </joint>
  </xacro:macro> 

  <xacro:wheel prefix="l" x_reflect="1" y_reflect="0.43" mirror="0" x="-0.135" y="-0.05" col_x="0" col_y="0.0" col_z="0"/>
  <xacro:wheel prefix="r" x_reflect="1" y_reflect="-0.47" mirror="3.15" x="0.135" y="0.065" col_x="0" col_y="0.015" col_z="0"/>



 
</robot>