teleop_twist_joy_node:
  ros__parameters:
    axis_linear:
      x: 1
    scale_linear:
      x: 0.25
    scale_linear_turbo:
      x: 0.5

    axis_angular:
      yaw: 0
    scale_angular:
      yaw: 0.4

    #enable_button: 4  # L2 shoulder button
    enable_button: 10  # L2 shoulder button
    enable_turbo_button: 5  # L1 shoulder button
